id: overview_the_data_has_been_split_into_tw_fdfb59
description: "Overview\n\nThe data has been split into two groups:\n\ntraining set\
  \ (train.csv)\ntest set (test.csv)\nThe training set should be used to build your\
  \ machine learning models. For the training set, we provide the outcome (also known\
  \ as the “ground truth”) for each passenger. Your model will be based on “features”\
  \ like passengers’ gender and class. You can also use feature engineering to create\
  \ new features.\n\nThe test set should be used to see how well your model performs\
  \ on unseen data. For the test set, we do not provide the ground truth for each\
  \ passenger. It is your job to predict these outcomes. For each passenger in the\
  \ test set, use the model you trained to predict whether or not they survived the\
  \ sinking of the Titanic.\n\nWe also include gender_submission.csv, a set of predictions\
  \ that assume all and only female passengers survive, as an example of what a submission\
  \ file should look like.\n\nData Dictionary\n\nVariable\tDefinition\tKey\nsurvival\t\
  Survival\t0 = No, 1 = Yes\npclass\tTicket class\t1 = 1st, 2 = 2nd, 3 = 3rd\nsex\t\
  Sex\t\nAge\tAge in years\t\nsibsp\t# of siblings / spouses aboard the Titanic\t\n\
  parch\t# of parents / children aboard the Titanic\t\nticket\tTicket number\t\nfare\t\
  Passenger fare\t\ncabin\tCabin number\t\nembarked\tPort of Embarkation\tC = Cherbourg,\
  \ Q = Queenstown, S = Southampton\nVariable Notes\n\npclass: A proxy for socio-economic\
  \ status (SES)\n1st = Upper\n2nd = Middle\n3rd = Lower\n\nage: Age is fractional\
  \ if less than 1. If the age is estimated, is it in the form of xx.5\n\nsibsp: The\
  \ dataset defines family relations in this way...\nSibling = brother, sister, stepbrother,\
  \ stepsister\nSpouse = husband, wife (mistresses and fiancés were ignored)\n\nparch:\
  \ The dataset defines family relations in this way...\nParent = mother, father\n\
  Child = daughter, son, stepdaughter, stepson\nSome children travelled only with\
  \ a nanny, therefore parch=0 for them."
metric: roc_auc
metric_higher_better: true
train_path: tasks/data/overview_the_data_has_been_split_into_tw_fdfb59/train.csv
test_features_path: tasks/data/overview_the_data_has_been_split_into_tw_fdfb59/test_features.csv
hidden_labels_path: tasks/hidden_labels/overview_the_data_has_been_split_into_tw_fdfb59/y_test.csv
